version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    container_name: mail
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
###< symfony/mailer ###
